const slugs = [
  "bihar",
  "west-bengal",
  "jharkhand",
  "odisha",
  "andaman-and-nicobar",
  "sikkim",
  "arunachal-pradesh",
  "mizoram",
  "meghalaya",
  "assam",
  "nagaland",
  "tripura",
  "manipur",
  //for south zone
  "andhra-pradesh",
  "karnataka",
  "kerala",
  "lakshadweep",
  "puducherry",
  "tamil-nadu",
  "telangana",
  //central zones
  "chhattisgarh",
  "madhya-pradesh",
  "maharashtra",
  "uttar-pradesh",
  //for west zone.
  "gujarat",
  "goa",
  "dadra-and-nagar-haveli-and-daman-and-diu",
  //for north zone....
  "chandigarh",
  "delhi",
  "haryana",
  "himachal-pradesh",
  "jammu-and-kashmir",
  "ladakh",
  "punjab",
  "uttarakhand",
];
const ISO = [
  "BR",
  "WB",
  "JH",
  "OR",
  "AN",
  "SK",
  "AR",
  "MZ",
  "ML",
  "AS",
  "NL",
  "TR",
  "MN",
  "AP",
  "KA",
  "KL",
  "LD",
  "PY",
  "TN",
  "TG",
  "CT",
  "MP",
  "MH",
  "UP",
  "GJ",
  "GA",
  "DN",
  "CH",
  "DL",
  "HR",
  "HP",
  "JK",
  "LA",
  "PB",
  "UT",
];
const images = [
  "https://res.cloudinary.com/techbuy/image/upload/v1642609186/COVID/BIHAR_le3fbq.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642655221/COVID/wb_pllhyb.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642654877/COVID/JHARKHAND_yde1fy.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642655319/COVID/odisha_xv6oom.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642655325/COVID/andaman_u4ryk8.jpg",
  "https://res.cloudinary.com/techbuy/image/upload/v1642686856/COVID/sikkim_cqnsio.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642686856/COVID/arunacahal_o2zulx.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642686855/COVID/mizoram_eeb6z5.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642686855/COVID/meghalaya_ldme2b.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642686856/COVID/assam_rnnhji.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642686855/COVID/naga_b8zyqm.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642686855/COVID/tripura_wsqdop.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642686854/COVID/manipur_gep4yl.png",
  //for south india
  "https://res.cloudinary.com/techbuy/image/upload/v1642689940/COVID/andhra_ofgjhj.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642689940/COVID/karnataka_njno7n.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642689939/COVID/kerala_qe3y5d.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642689939/COVID/lakshadweep_mfqxeo.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642689940/COVID/pudu_hnwcpf.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642689940/COVID/tamil_ihd4ln.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642689939/COVID/telangana_w19nhe.png",
  //central zone.........
  "https://res.cloudinary.com/techbuy/image/upload/v1642690196/COVID/chhatisg_hnqvlu.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642690196/COVID/mp_njzgjc.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642690196/COVID/maharashtra_ym1ptt.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642690196/COVID/up_gii2f2.png",
  //west zone.........
  "https://res.cloudinary.com/techbuy/image/upload/v1642690352/COVID/gujarat_euzy9j.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642690352/COVID/ddd_ncck65.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642690352/COVID/ddd_ncck65.png",
  //north india.....
  "https://res.cloudinary.com/techbuy/image/upload/v1642690639/COVID/chandigarh_ne8dx6.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642690640/COVID/delhi_evkiws.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642690640/COVID/haryana_dvm6io.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642690639/COVID/himachal_ztab98.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642690639/COVID/jk_gyzbwn.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642690638/COVID/ladakh_bixucp.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642690638/COVID/punja_pdrxyg.png",
  "https://res.cloudinary.com/techbuy/image/upload/v1642690638/COVID/punja_pdrxyg.png",
];
const name = [
  "Bihar",
  "West Bengal",
  "Jharkhand",
  "Odisha",
  "Andaman and Nicobar",
  "Sikkim",
  "Arunachal Pradesh",
  "Mizoram",
  "Meghalaya",
  "Assam",
  "Nagaland",
  "Tripura",
  "Manipur",
  "Andhra Pradesh",
  "Karnataka",
  "Kerala",
  "Lakshadweep",
  "Puducherry",
  "Tamil Nadu",
  "Telangana",
  "Chhattisgarh",
  "Madhya Pradesh",
  "Maharashtra",
  "Uttar Pradesh",
  "Gujarat",
  "Goa",
  "Dadra and Nagar Haveli and Daman & Diu",
  "Chandigarh",
  "Delhi",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Ladakh",
  "Punjab",
  "Uttarakhand",
];

export { slugs, ISO, images, name };
